2014/02/19 13:50:06 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (D:\wamp\www\yii\framework\YiiBase.php:427)
Stack trace:
#0 D:\wamp\www\yii\finao\protected\components\UserIdentity.php(13): spl_autoload_call()
#1 D:\wamp\www\yii\finao\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 D:\wamp\www\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 D:\wamp\www\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 D:\wamp\www\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 D:\wamp\www\yii\finao\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 D:\wamp\www\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 D:\wamp\www\yii\framework\web\CController.php(286): SiteController->runAction()
#9 D:\wamp\www\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 D:\wamp\www\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 D:\wamp\www\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 D:\wamp\www\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 D:\wamp\www\yii\finao\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/finao/index.php?r=site/login
in D:\wamp\www\yii\finao\protected\components\UserIdentity.php (13)
in D:\wamp\www\yii\finao\protected\models\LoginForm.php (52)
in D:\wamp\www\yii\finao\protected\controllers\SiteController.php (94)
2014/02/19 13:51:03 [error] [php] include(User.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (D:\wamp\www\yii\framework\YiiBase.php:427)
Stack trace:
#0 D:\wamp\www\yii\finao\protected\components\UserIdentity.php(13): spl_autoload_call()
#1 D:\wamp\www\yii\finao\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 D:\wamp\www\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 D:\wamp\www\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 D:\wamp\www\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 D:\wamp\www\yii\finao\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 D:\wamp\www\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 D:\wamp\www\yii\framework\web\CController.php(286): SiteController->runAction()
#9 D:\wamp\www\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 D:\wamp\www\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 D:\wamp\www\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 D:\wamp\www\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 D:\wamp\www\yii\finao\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/finao/index.php?r=site/login
in D:\wamp\www\yii\finao\protected\components\UserIdentity.php (13)
in D:\wamp\www\yii\finao\protected\models\LoginForm.php (52)
in D:\wamp\www\yii\finao\protected\controllers\SiteController.php (94)
2014/02/19 13:51:45 [error] [exception.CDbException] exception 'CDbException' with message 'Table "fn_users" does not have a column named "username".' in D:\wamp\www\yii\framework\db\schema\CDbCommandBuilder.php:694
Stack trace:
#0 D:\wamp\www\yii\framework\db\ar\CActiveRecord.php(1518): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 D:\wamp\www\yii\finao\protected\components\UserIdentity.php(13): CActiveRecord->findByAttributes(Array)
#2 D:\wamp\www\yii\finao\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 D:\wamp\www\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 D:\wamp\www\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 D:\wamp\www\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 D:\wamp\www\yii\finao\protected\controllers\SiteController.php(94): CModel->validate()
#7 D:\wamp\www\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 D:\wamp\www\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\wamp\www\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 D:\wamp\www\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\wamp\www\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 D:\wamp\www\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 D:\wamp\www\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 D:\wamp\www\yii\finao\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/yii/finao/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/finao/index.php?r=site/login
---
2014/02/19 14:08:07 [error] [php] Object of class LoginForm could not be converted to string (D:\wamp\www\yii\finao\protected\controllers\SiteController.php:92)
Stack trace:
#0 D:\wamp\www\yii\framework\web\CController.php(286): SiteController->runAction()
#1 D:\wamp\www\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 D:\wamp\www\yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 D:\wamp\www\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\wamp\www\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\wamp\www\yii\finao\index.php(13): CWebApplication->run()
REQUEST_URI=/yii/finao/index.php?r=site/login
in D:\wamp\www\yii\finao\protected\controllers\SiteController.php (92)
in D:\wamp\www\yii\finao\index.php (13)
